### ISSUE TITLE
Installer exits after entering Administrator password

### ISSUE THREAD

**Issue by noetico** [flexcomng/erpnext_quick_install#20]
I've just come across this fine script. I noticed an issue trying to use this in Ubuntu and Debian; at the point where you insert the admin user passwords; the script causes Putty to exit immediately with no warnings. There are no error messages but it happens after you enter the site name and admin password.

**Comment by Rebaz-balisani** [comment]
i have the same issue and i have informed them on discus session

**Comment by flexcomng** [comment]
I am unable to replicate this issue as i have tested on ubuntu 22.04 and 24.04 installing version 15. So it would help if you could share the exact error you're getting by sharing your OS version and the ERPNext version you're trying to install. Because the script is a bash script, it tends to teminate the terminal connection if there's an error so if you use clients like putty or vscode to connect this might lead to session termination. 

To be able to see the error, please ssh using terminal if you're using Mac or Linux systems or command prompt if you're using windows. If the connection terminates during install, you will still be able to see the last outputs before the session termination. Kindly therefore share the error you see and i'll use it to troubleshoot the issue you might be encountering.

**Comment by Rebaz-balisani** [comment]
please if you have time, i can share my screen via Anydesk, here is my email: rebaz.balisani@gmail.com, i can share my vps as well

**Comment by ManuelPipe** [comment]
same issue:

Now setting up your site. This might take a few minutes. Please wait...
chmod: cannot access '/home/root': No such file or directory
An error occurred on line 367 with exit status 0

**Comment by flexcomng** [comment]
> Now setting up your site. This might take a few minutes. Please wait...chmod: cannot access '/home/root': No such file or directory

This suggests that you're running the script either as root or with elevated privilges hence the script is trying to install bench/site in the root user's directory. Please run the script as a non-root user and do not run the script using sudo.

**Comment by Rebaz-balisani** [comment]
Hi @flexcomng ,
thanks for your spirit of support and sharing 
(in my case it was always exiting after i was adding ADMIN password after I did below the installation went smoothly and successfully)

Plese add below code to your README page after "sudo apt update && sudo apt -y upgrade" as it will be helping dozens of new learners.

1. **sudo su root**
2. **sudo adduser frappeuser**
        Full Name []: **frappeuser**
	Room Number []: 
	Work Phone []: 
	Home Phone []: 
'	Other []: 
        Is the information correct? [Y]
3.**usermod -aG sudo frappeuser**
4.**su frappeuser** 
5.**cd /home/frappeuser**
