### ISSUE TITLE
Is an upgrade of erpnext (eg from v14 to v15) available with this script

### ISSUE THREAD

**Issue by cgiakmoz** [flexcomng/erpnext_quick_install#25]
For example, after a previous successful install of ErpNext version 14 6 months ago, I would like to upgrade to Version 15.

Is it best to just do a fresh install from scratch on a clean OS, and then import a backup of the Old set of books from Version  14 ? Or can this easy-install script be made to handle upgrading the operating system, bench, frappe-bench, and erpnext generally?

**Comment by flexcomng** [comment]
It is very tricky to handle version upgrades with a script because every instance is unique and while in some cases, the standard upgrade steps might work for an instance, it is not uncommon to find additional steps required during major version upgrades so it is unwise to use a script for this process.

For your question, it is much easier to make a fresh install and database restore for upgrade to version 15 as you do not need to concern yourself with dependency issues which may occur while using the standard upgrade commands. However, due to resource constraints, it may not be feasible for you to set up a brand new instance for upgrade. So your experience may vary so you should consider your circumstances and options carefully before deciding how to move forward.

**Comment by cgiakmoz** [comment]
Thank you for your reply. Its as I suspected. 8-)
At least a fresh installation script with only 4 commands is a blessing.
